import {
  type CategoryDataResponse,
  type TransactionDataResponse,
  type UserDataResponse,
  type WalletDataResponse,
} from 'data/types'

export const dummyUsersData: UserDataResponse[] = [
  {
    id: 'useruseruseruser-001',
    username: 'user001',
    email: 'user001@mail.com',
    fullname: 'User 001',
    image_url: undefined,
    parent_id: undefined,
    created_at: new Date('2023-02-01'),
    updated_at: new Date('2023-02-01'),
    deleted_at: undefined,
  },
  {
    id: 'useruseruseruser-002',
    username: 'user002',
    email: 'user002@mail.com',
    fullname: 'User 002',
    image_url: undefined,
    parent_id: 'useruseruseruser-001',
    created_at: new Date('2023-02-01'),
    updated_at: new Date('2023-02-01'),
    deleted_at: undefined,
  },
]

export const dummyWalletssData: WalletDataResponse[] = [
  {
    id: 'walletwalletxxxx-001',
    name: 'Wallet 001',
    balance: 2000000,
    is_owner: true,
    user_id: dummyUsersData[0].id,
    user_name: dummyUsersData[0].username,
    user_fullname: dummyUsersData[0].fullname,
    created_at: new Date('2023-02-01'),
    updated_at: new Date('2023-02-01'),
    deleted_at: undefined,
  },
  {
    id: 'walletwalletxxxx-002',
    name: 'Wallet 002',
    balance: 2000000,
    is_owner: true,
    user_id: dummyUsersData[0].id,
    user_name: dummyUsersData[0].username,
    user_fullname: dummyUsersData[0].fullname,
    created_at: new Date('2023-02-01'),
    updated_at: new Date('2023-02-01'),
    deleted_at: undefined,
  },
  {
    id: 'walletwalletxxxx-003',
    name: 'Wallet 003',
    balance: 2000000,
    is_owner: false,
    user_id: dummyUsersData[1].id,
    user_name: dummyUsersData[1].username,
    user_fullname: dummyUsersData[1].fullname,
    created_at: new Date('2023-02-01'),
    updated_at: new Date('2023-02-01'),
    deleted_at: undefined,
  },
  {
    id: 'walletwalletxxxx-004',
    name: 'Wallet 004',
    balance: 2000000,
    is_owner: false,
    user_id: dummyUsersData[1].id,
    user_name: dummyUsersData[1].username,
    user_fullname: dummyUsersData[1].fullname,
    created_at: new Date('2023-02-01'),
    updated_at: new Date('2023-02-01'),
    deleted_at: undefined,
  },
]

export const dummyCategoriesData: CategoryDataResponse[] = [
  {
    id: 'categorycategory-001',
    name: 'Category 001',
    icon_url: undefined,
    group: 'Required Expense',
    is_owner: true,
    user_id: dummyUsersData[0].id,
    user_name: dummyUsersData[0].username,
    user_fullname: dummyUsersData[0].fullname,
    transaction_type: 'out',
    created_at: new Date('2023-02-04'),
    updated_at: new Date('2023-02-04'),
    deleted_at: undefined,
  },
  {
    id: 'categorycategory-002',
    name: 'Category 002',
    icon_url: undefined,
    group: 'Fun and Relax',
    is_owner: true,
    user_id: dummyUsersData[0].id,
    user_name: dummyUsersData[0].username,
    user_fullname: dummyUsersData[0].fullname,
    transaction_type: 'out',
    created_at: new Date('2023-02-04'),
    updated_at: new Date('2023-02-04'),
    deleted_at: undefined,
  },
  {
    id: 'categorycategory-003',
    name: 'Category 003',
    icon_url: undefined,
    group: 'Income',
    is_owner: true,
    user_id: dummyUsersData[0].id,
    user_name: dummyUsersData[0].username,
    user_fullname: dummyUsersData[0].fullname,
    transaction_type: 'in',
    created_at: new Date('2023-02-04'),
    updated_at: new Date('2023-02-04'),
    deleted_at: undefined,
  },
  {
    id: 'categorycategory-004',
    name: 'Category 004',
    icon_url: undefined,
    group: 'Income',
    is_owner: false,
    user_id: dummyUsersData[1].id,
    user_name: dummyUsersData[1].username,
    user_fullname: dummyUsersData[1].fullname,
    transaction_type: 'in',
    created_at: new Date('2023-02-04'),
    updated_at: new Date('2023-02-04'),
    deleted_at: undefined,
  },
  {
    id: 'categorycategory-005',
    name: 'Category 005',
    icon_url: undefined,
    group: 'Invensting and Debt Payment',
    is_owner: false,
    user_id: dummyUsersData[1].id,
    user_name: dummyUsersData[1].username,
    user_fullname: dummyUsersData[1].fullname,
    transaction_type: 'out',
    created_at: new Date('2023-02-04'),
    updated_at: new Date('2023-02-04'),
    deleted_at: undefined,
  },
]

export const dummyTransactionsData: TransactionDataResponse[] = [
  {
    id: 'transactionxxxxx-001',
    amount: 120000,
    date: new Date('2023-02-14'),
    description: 'This is transaction 001',
    image_url: undefined,
    transaction_type: dummyCategoriesData[0].transaction_type,
    category_id: dummyCategoriesData[0].id,
    category_name: dummyCategoriesData[0].name,
    user_id: dummyCategoriesData[0].user_id,
    user_name: dummyCategoriesData[0].user_name,
    user_fullname: dummyCategoriesData[0].user_fullname,
    wallet_id: dummyWalletssData[0].id,
    wallet_name: dummyWalletssData[0].name,
    is_owner: true,
    created_at: new Date('2023-02-14'),
    updated_at: new Date('2023-02-14'),
    deleted_at: undefined,
  },
  {
    id: 'transactionxxxxx-002',
    amount: 200000,
    date: new Date('2023-02-14'),
    description: 'This is transaction 002',
    image_url: undefined,
    transaction_type: dummyCategoriesData[2].transaction_type,
    category_id: dummyCategoriesData[2].id,
    category_name: dummyCategoriesData[2].name,
    user_id: dummyCategoriesData[2].user_id,
    user_name: dummyCategoriesData[2].user_name,
    user_fullname: dummyCategoriesData[2].user_fullname,
    wallet_id: dummyWalletssData[0].id,
    wallet_name: dummyWalletssData[0].name,
    is_owner: true,
    created_at: new Date('2023-02-14'),
    updated_at: new Date('2023-02-14'),
    deleted_at: undefined,
  },
  {
    id: 'transactionxxxxx-003',
    amount: 88000,
    date: new Date('2023-02-17'),
    description: 'This is transaction 003',
    image_url: undefined,
    transaction_type: dummyCategoriesData[1].transaction_type,
    category_id: dummyCategoriesData[1].id,
    category_name: dummyCategoriesData[1].name,
    user_id: dummyCategoriesData[1].user_id,
    user_name: dummyCategoriesData[1].user_name,
    user_fullname: dummyCategoriesData[1].user_fullname,
    wallet_id: dummyWalletssData[0].id,
    wallet_name: dummyWalletssData[0].name,
    is_owner: true,
    created_at: new Date('2023-02-17'),
    updated_at: new Date('2023-02-17'),
    deleted_at: undefined,
  },
  {
    id: 'transactionxxxxx-004',
    amount: 250000,
    date: new Date('2023-02-15'),
    description: 'This is transaction 004',
    image_url: undefined,
    transaction_type: dummyCategoriesData[2].transaction_type,
    category_id: dummyCategoriesData[2].id,
    category_name: dummyCategoriesData[2].name,
    user_id: dummyCategoriesData[2].user_id,
    user_name: dummyCategoriesData[2].user_name,
    user_fullname: dummyCategoriesData[2].user_fullname,
    wallet_id: dummyWalletssData[1].id,
    wallet_name: dummyWalletssData[1].name,
    is_owner: true,
    created_at: new Date('2023-02-15'),
    updated_at: new Date('2023-02-15'),
    deleted_at: undefined,
  },
  {
    id: 'transactionxxxxx-005',
    amount: 75000,
    date: new Date('2023-02-14'),
    description: 'This is transaction 005',
    image_url: undefined,
    transaction_type: dummyCategoriesData[3].transaction_type,
    category_id: dummyCategoriesData[3].id,
    category_name: dummyCategoriesData[3].name,
    user_id: dummyCategoriesData[3].user_id,
    user_name: dummyCategoriesData[3].user_name,
    user_fullname: dummyCategoriesData[3].user_fullname,
    wallet_id: dummyWalletssData[2].id,
    wallet_name: dummyWalletssData[2].name,
    is_owner: false,
    created_at: new Date('2023-02-14'),
    updated_at: new Date('2023-02-14'),
    deleted_at: undefined,
  },
  {
    id: 'transactionxxxxx-006',
    amount: 120000,
    date: new Date('2023-02-20'),
    description: 'This is transaction 006',
    image_url: undefined,
    transaction_type: dummyCategoriesData[4].transaction_type,
    category_id: dummyCategoriesData[4].id,
    category_name: dummyCategoriesData[4].name,
    user_id: dummyCategoriesData[4].user_id,
    user_name: dummyCategoriesData[4].user_name,
    user_fullname: dummyCategoriesData[4].user_fullname,
    wallet_id: dummyWalletssData[2].id,
    wallet_name: dummyWalletssData[2].name,
    is_owner: false,
    created_at: new Date('2023-02-20'),
    updated_at: new Date('2023-02-20'),
    deleted_at: undefined,
  },
  {
    id: 'transactionxxxxx-001',
    amount: 120000,
    date: new Date('2023-02-14'),
    description: 'This is transaction 001',
    image_url: undefined,
    transaction_type: dummyCategoriesData[3].transaction_type,
    category_id: dummyCategoriesData[3].id,
    category_name: dummyCategoriesData[3].name,
    user_id: dummyCategoriesData[3].user_id,
    user_name: dummyCategoriesData[3].user_name,
    user_fullname: dummyCategoriesData[3].user_fullname,
    wallet_id: dummyWalletssData[3].id,
    wallet_name: dummyWalletssData[3].name,
    is_owner: false,
    created_at: new Date('2023-02-14'),
    updated_at: new Date('2023-02-14'),
    deleted_at: undefined,
  },
  {
    id: 'transactionxxxxx-001',
    amount: 120000,
    date: new Date('2023-02-14'),
    description: 'This is transaction 001',
    image_url: undefined,
    transaction_type: dummyCategoriesData[4].transaction_type,
    category_id: dummyCategoriesData[4].id,
    category_name: dummyCategoriesData[4].name,
    user_id: dummyCategoriesData[4].user_id,
    user_name: dummyCategoriesData[4].user_name,
    user_fullname: dummyCategoriesData[4].user_fullname,
    wallet_id: dummyWalletssData[3].id,
    wallet_name: dummyWalletssData[3].name,
    is_owner: false,
    created_at: new Date('2023-02-14'),
    updated_at: new Date('2023-02-14'),
    deleted_at: undefined,
  },
]
